# Generated by Django 3.2.4 on 2021-07-24 14:58

from django.db import migrations, models
import django.db.models.deletion
import emp_pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up_Docs',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hr_pages.userdata')),
                ('aadhar_card', models.FileField(blank=True, default=None, null=True, upload_to=emp_pages.models.user_directory_path)),
                ('pan_card', models.FileField(blank=True, default=None, null=True, upload_to=emp_pages.models.user_directory_path)),
                ('passport', models.FileField(blank=True, default=None, null=True, upload_to=emp_pages.models.user_directory_path)),
                ('driving_license', models.FileField(blank=True, default=None, null=True, upload_to=emp_pages.models.user_directory_path)),
                ('aadhar_status', models.CharField(default='Processing', max_length=15)),
                ('pan_status', models.CharField(default='Processing', max_length=15)),
                ('passport_status', models.CharField(default='Processing', max_length=15)),
                ('driving_status', models.CharField(default='Processing', max_length=15)),
            ],
        ),
    ]
