# Generated by Django 3.2.4 on 2021-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='group_name',
            field=models.CharField(default='Sales', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
    ]
