# Generated by Django 3.2.4 on 2021-07-25 11:06

from django.db import migrations, models
import hr_pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='prof_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=hr_pages.models.user_directory_path),
        ),
    ]
